/**
 * Vault scaffold helper — extracted from agent-lab/scripts/vo-cli.ts
 * vaultInit() so both the CLI and the local dashboard
 * (VO-LOCAL-VAULT-DASHBOARD-PR-1) can initialize a vault layout without
 * either needing to import the other.
 *
 * What this module does:
 *   - accepts (root, tenantId) plus optional inputs
 *   - creates the canonical vault directory tree
 *   - writes the marker file (.vo-vault.json) with tenant binding
 *   - writes the standard scaffold documents
 *   - never writes to the graph, never harvests, never calls external APIs
 *
 * What this module does NOT do:
 *   - parse CLI flags (it takes a typed argument object)
 *   - call process.exit() (it throws on error — callers decide how to surface)
 *   - mutate ~/.vo/config.json (that's a dashboard / CLI concern, not scaffold)
 *   - call into any CLI script (zero dependency on agent-lab/*)
 *
 * The CLI's existing vaultInit() keeps its own richer docs for now; this
 * module emits a minimal faithful scaffold that `vo vault harvest/confirm/
 * finalize` can operate on. Both CLI and dashboard produce a vault with
 * the same .vo-vault.json binding and the same directory layout, so they
 * are interchangeable as inputs to the harvest pipeline.
 */

import * as fs from "node:fs";
import * as path from "node:path";

// ─── Errors ─────────────────────────────────────────────────────────────

export class VaultScaffoldError extends Error {
  constructor(
    public readonly reason:
      | "not_absolute"
      | "tenant_mismatch"
      | "marker_unreadable"
      | "write_failed",
    message: string,
    public readonly details?: Record<string, unknown>,
  ) {
    super(message);
    this.name = "VaultScaffoldError";
  }
}

// ─── Types ──────────────────────────────────────────────────────────────

export interface ScaffoldVaultInput {
  /** Absolute filesystem path where the vault should live. */
  root: string;
  /** Tenant id to bind the vault to via .vo-vault.json. */
  tenantId: string;
  /** Optional VO API URL stored inside .vo-vault.json. Defaults to the
   *  convention used by the CLI (http://localhost:3100). */
  voUrl?: string;
}

export type ScaffoldAction = "created" | "unchanged" | "updated";

export interface ScaffoldVaultResult {
  root: string;
  tenant_id: string;
  created_count: number;
  updated_count: number;
  unchanged_count: number;
  files: Record<string, ScaffoldAction>;
}

// ─── Scaffold content ───────────────────────────────────────────────────
//
// The exact strings here are idempotent: re-running scaffoldVault() on an
// existing vault with matching content returns "unchanged" for every file,
// which makes the operation safe to call from a POST /dashboard/vault/init
// that the operator may retry.

const AGENTS_MD = `# VO Vault — Agent Contract

This vault is a companion layer to a Verity One knowledge graph.
Read .vo-vault.json for the VO API URL and tenant identity.

## Vault Zones

### captures/ — IMMUTABLE
You must NEVER modify, delete, or rename files in captures/.
These are source documents. They are append-only.

### dossiers/*.dossier.draft.md — EDITABLE (curation surface)
You may edit the fenced yaml atom block in draft dossiers to improve accuracy.
You may adjust confidence levels and source_section references.
You must not change the frontmatter fields: capture_hash, source_capture, vo_type.

### dossiers/*.dossier.md — READ-ONLY (generated)
You must not edit finalized dossiers. They are managed by the harvest pipeline.
If you need to annotate a dossier, create a note in notes/ instead.

### notes/ — HUMAN-OWNED
You may read notes for context. You must never create, modify, or delete notes
unless the human explicitly asks you to.

### index.md, log.md — MANAGED
You must not edit these directly. They are regenerated by the harvest pipeline.

### inbox/web-clips/ — INTAKE (clipper drop zone)
The Obsidian Web Clipper saves pages here. These are intake artifacts, not captures.
You may read them for context. Harvest them with vo vault harvest to ingest into VO.
You must not modify or delete clipper notes — the human manages this folder.

### docs/ — REFERENCE
You may read docs/ for vault usage guidance. You must not modify these files.

## Authority
The VO graph (accessed via the VO API at the URL in .vo-vault.json) is the
canonical source of truth for all assertions. Dossiers are curated summaries.
If a dossier contradicts the graph, the graph wins.

## Source Refs
When writing to the VO graph, source_refs must point to files in captures/
using the paths recorded in dossier frontmatter. Never fabricate source paths.

## File Identity
Generated filenames use the pattern {hash8}-{slug}.{ext} where hash8 is the
first 8 hex characters of the capture file's sha256 hash. The slug is cosmetic.
Use the hash prefix for lookup, not the slug.
`;

const CLAUDE_MD = `# VO Vault

All vault rules, zone permissions, and authority model are defined in AGENTS.md
in this directory. Read AGENTS.md before taking any action in this vault.

See docs/vault-guide.md for human-facing setup and usage documentation.
`;

const GITIGNORE = `# Obsidian workspace (changes per machine)
.obsidian/workspace.json
.obsidian/workspace-mobile.json

# OS
.DS_Store

# Large binaries (add patterns as needed)
# raw/images/*.psd
# raw/data/*.csv
`;

const INDEX_MD = `# Vault Index

| Dossier | Date | Atoms | Source |
|---------|------|-------|--------|

*0 sources captured. 0 assertions in VO.*
`;

const VAULT_GUIDE_MD = `# VO Vault Guide

The vault is a local markdown companion layer for readable dossiers and notes.
It stays on your machine. Obsidian is optional.

## Getting started

1. Verify your vault root exists and contains \`.vo-vault.json\`.
2. Keep VO running at the URL recorded in \`.vo-vault.json\` (defaults to
   \`http://localhost:3100\`).
3. Open the vault directory in your file manager, or open it as a vault in
   Obsidian if you have it installed.

## Layout

- \`captures/\` — immutable source documents (append-only).
- \`dossiers/\` — curated draft + finalized dossiers.
- \`notes/\` — your private annotations; VO does not read this folder.
- \`inbox/web-clips/\` — intake drop zone for the Obsidian Web Clipper.
- \`docs/\` — reference (this file).
- \`log.md\` — append-only operation log.
- \`index.md\` — regenerated catalog of finalized dossiers.

## Harvest pipeline

Use the VO CLI from the machine running the API:

\`\`\`
bun run agent-lab/scripts/vo-cli.ts vault harvest --root <vault-path> <source>
bun run agent-lab/scripts/vo-cli.ts vault confirm --root <vault-path> <hash8>
bun run agent-lab/scripts/vo-cli.ts vault finalize --root <vault-path> <hash8>
\`\`\`

Dashboard initialization only creates the scaffold; harvest remains a CLI
operation in this release.

## Authority

The VO graph is the canonical source of truth for all assertions. Dossiers
are curated summaries. Local authority stays local — the dashboard and CLI
are the only first-class Vault controls at this time.
`;

function initLogEntry(tenantId: string, vaultRoot: string, now: string): string {
  return `# Operation Log

## [${now}] init | Vault initialized
- **Tenant:** ${tenantId}
- **Root:** ${vaultRoot}
- **Created:** AGENTS.md, CLAUDE.md, .vo-vault.json, .gitignore, index.md, log.md, docs/vault-guide.md
- **Directories:** captures/, dossiers/, dossiers/.conflicts/, notes/, docs/, inbox/, inbox/web-clips/, .obsidian/
`;
}

// ─── Atomic helpers ─────────────────────────────────────────────────────

function writeIfChanged(absPath: string, content: string): ScaffoldAction {
  if (fs.existsSync(absPath)) {
    try {
      const existing = fs.readFileSync(absPath, "utf-8");
      if (existing === content) return "unchanged";
    } catch {
      // Unreadable — fall through to overwrite (we own the scaffold files)
    }
    fs.writeFileSync(absPath, content, "utf-8");
    return "updated";
  }
  fs.writeFileSync(absPath, content, "utf-8");
  return "created";
}

function writeOnlyIfMissing(absPath: string, content: string): ScaffoldAction {
  if (fs.existsSync(absPath)) return "unchanged";
  fs.writeFileSync(absPath, content, "utf-8");
  return "created";
}

// ─── Public API ─────────────────────────────────────────────────────────

/**
 * Create or update the vault scaffold at `input.root`, binding it to
 * `input.tenantId` via `.vo-vault.json`. Idempotent: re-running on an
 * existing vault with matching content returns "unchanged" for every file.
 *
 * Throws `VaultScaffoldError` with reason="tenant_mismatch" if the root
 * already has a `.vo-vault.json` pointing at a different tenant. The
 * caller (CLI or dashboard route) decides how to surface that — this
 * helper never force-rebinds.
 */
export function scaffoldVault(input: ScaffoldVaultInput): ScaffoldVaultResult {
  const root = input.root;
  if (!path.isAbsolute(root)) {
    throw new VaultScaffoldError(
      "not_absolute",
      `vault root must be an absolute path: ${JSON.stringify(root)}`,
      { root },
    );
  }

  const tenantId = input.tenantId;
  const voUrl = (input.voUrl || "http://localhost:3100").trim();
  const now = new Date().toISOString();

  // Directories — order irrelevant, recursive mkdir is idempotent.
  const dirs = [
    root,
    path.join(root, "captures"),
    path.join(root, "dossiers"),
    path.join(root, "dossiers", ".conflicts"),
    path.join(root, "notes"),
    path.join(root, "docs"),
    path.join(root, "inbox"),
    path.join(root, "inbox", "web-clips"),
    path.join(root, ".obsidian"),
  ];
  for (const dir of dirs) {
    fs.mkdirSync(dir, { recursive: true });
  }

  const files: Record<string, ScaffoldAction> = {};

  // .vo-vault.json — marker file. Tenant binding is load-bearing: existing
  // marker with a different tenant_id must fail rather than force-rebind.
  const markerPath = path.join(root, ".vo-vault.json");
  if (fs.existsSync(markerPath)) {
    let existingTenantId: string | null = null;
    try {
      const parsed = JSON.parse(fs.readFileSync(markerPath, "utf-8"));
      existingTenantId = typeof parsed.tenant_id === "string" ? parsed.tenant_id : null;
    } catch (e) {
      throw new VaultScaffoldError(
        "marker_unreadable",
        `.vo-vault.json at ${markerPath} is not valid JSON: ${(e as Error).message}`,
        { root, markerPath },
      );
    }
    if (existingTenantId && existingTenantId !== tenantId) {
      throw new VaultScaffoldError(
        "tenant_mismatch",
        `vault at ${root} is bound to tenant "${existingTenantId}", but init was called with tenant "${tenantId}"`,
        { root, existing_tenant_id: existingTenantId, requested_tenant_id: tenantId },
      );
    }
    files[".vo-vault.json"] = "unchanged";
  } else {
    const marker = JSON.stringify(
      {
        tenant_id: tenantId,
        vo_url: voUrl,
        schema_version: 1,
        vo_version: "0.1.0",
        vault_version: "1.0.0",
        created_at: now,
      },
      null,
      2,
    ) + "\n";
    fs.writeFileSync(markerPath, marker, "utf-8");
    files[".vo-vault.json"] = "created";
  }

  files["AGENTS.md"] = writeIfChanged(path.join(root, "AGENTS.md"), AGENTS_MD);
  files["CLAUDE.md"] = writeIfChanged(path.join(root, "CLAUDE.md"), CLAUDE_MD);
  files[".gitignore"] = writeIfChanged(path.join(root, ".gitignore"), GITIGNORE);
  files["index.md"] = writeIfChanged(path.join(root, "index.md"), INDEX_MD);
  files["docs/vault-guide.md"] = writeIfChanged(path.join(root, "docs", "vault-guide.md"), VAULT_GUIDE_MD);

  // log.md is append-only: create only if missing; never overwrite prior
  // log entries even if we are re-running scaffold.
  files["log.md"] = writeOnlyIfMissing(path.join(root, "log.md"), initLogEntry(tenantId, root, now));

  // captures/.manifest.jsonl — empty intake manifest, create if missing.
  files["captures/.manifest.jsonl"] = writeOnlyIfMissing(
    path.join(root, "captures", ".manifest.jsonl"),
    "",
  );

  const created_count = Object.values(files).filter((v) => v === "created").length;
  const updated_count = Object.values(files).filter((v) => v === "updated").length;
  const unchanged_count = Object.values(files).filter((v) => v === "unchanged").length;

  return {
    root,
    tenant_id: tenantId,
    created_count,
    updated_count,
    unchanged_count,
    files,
  };
}
